### PR TITLE
New ai

### PR DESCRIPTION
**Pull request by Xilmi**
I hope I did it right. I made a new branch based on the new-ai-branch then merged my changes from the other branch into it and am now attempting a pull-request.
From next time on I'll always do the rebase-thing.

It would be nice if you could make a new build from the current state and send me the link somehow. :)

### CODE REVIEW

**Comment by MeridianOXC** [comment]
Github doesn't allow me to merge this, there are rebase-merge conflicts.
Also, all things that I complained about are still there!
There are still manual merges, duplicate commits (for example the 3 from yanke), reverts, etc.
I am not going to merge it like this, even if it was possible.

If you want, I can squash all 27 commits in this PR into a single commit, but you will lose the commit history.
Is that acceptable?

**Comment by MeridianOXC** [comment]
Or tell me which exact branch (final commit ID) should I take from your repo, and I will force-push your branch into my repo without a PR.

**Comment by MeridianOXC** [comment]
Also, I hope you see why I accept only finished features.
To avoid exactly this mess.

**Comment by Xilmi** [comment]
It's weird that you get these when I didn't get any warnings about this PR.
I don't really care about the commit-history and would be fine with the suggestion of pushing it in a single commit.
The branch from my repo to use would be "new-ai".

**Pull request merged**
