### PR TITLE
Hovering units full 3D flight

### PR DESCRIPTION
**Pull request by GixG**
Enables full 3D flight (vertical + horizontal simultaneously) for hovering units

### CODE REVIEW

**Comment by MeridianOXC** [comment]
Well... this is a hard one.
I see a lot of work has been invested into this, but I probably can't take it:
1. Pathfinding is the source of the worst bugs and headaches in Openxcom (or at least in the top 3)
2. I don't know if I can support/maintain/fix this feature in the future
3. Merging vanilla pathfinding fixes becomes harder
I will leave the PR open if anyone wants to cherry-pick it into their own repo, but it (probably) won't be merged.

**Comment by GixG** [comment]
I play with it for some time (I had proposed to OXC since... 2016 ??? - or
even before, and got tired of updating it on github). Finally he suggested
to try to see if you're willing to accept it... Finally. I switched to
OXCE, and updated it also...

În mar., 30 oct. 2018 la 10:37, Meridian <notifications@github.com> a scris:

**Comment by GixG** [comment]
SRRY - make it 2013...

În mar., 30 oct. 2018 la 12:52, Gix <gix.goger@gmail.com> a scris:

**Comment by MeridianOXC** [comment]
I see.
SupSuper probably had similar reasons as me for not taking the change.

**Comment by MeridianOXC** [comment]
Closing as "unwanted feature".

**Pull request closed without merging**
