### PR TITLE
Removed Quit option and Win self update code

### PR DESCRIPTION
**Pull request by daedalia**
Removed the Quit button as iOS apps don't really quit, against the ethos blah, blah. There is a quit function but that closes the app and leaves it in a crashed like state with the app window still front and centre.

Stripped out update code, probably shouldn't have, didn't seem to belong there really.

### CODE REVIEW

**Comment by MeridianOXC** [comment]
So, how does an iOS user restart the app, when they for example installed a new mod and need to restart the game to detect it?

**Comment by daedalia** [comment]
They go to the iOS task switcher and swipe up to kill the app, and tap the app again.

In it's current state, the Quit button returns the app to a black screen, not the home screen. If the user wants to run the game again, they have to perform above steps anyway otherwise they go back to the black screen when they tap the app icon, which is a worse experience I think and leads to confusion (there was a post in the forum about this). 

There is a way to do this I've read, it's probably not implemented in SDL because it's use would result in an app store rejection. Once I learn a little more I can revisit at a later date.

**Comment by daedalia** [comment]
I'm assuming there's a quit method you call in SDL that performs the necessary quit function on the target platform.

**Comment by MeridianOXC** [comment]
Merged manually. I've just hidden the Quit button. One day I want to unify the PC/Android/iOS code base, so removing PC code is not desired (in the interest of easier merging).

**Comment by daedalia** [comment]
Good point, my OCD got the better of me.

**Pull request closed without merging**
