### PR TITLE
Extended branding, icon & launch screen

### PR DESCRIPTION
**Pull request by daedalia**
OpenXcom Extended icon because it's nicer.
Launch screen replaced, current one comes from OG content, higher resolution.
Coloured the storyboard background to match image background, neater.

### CODE REVIEW

**Comment by MeridianOXC** [comment]
OXCE has a different branding than OXC (pink/red icon instead of a green/teal icon). I'll share the official icons via the forum later.

**Comment by daedalia** [comment]
Did you share those assets in the end?

**Comment by MeridianOXC** [comment]
Shared here: https://openxcom.org/forum/index.php/topic,8327.msg129676.html#msg129676

**Comment by MeridianOXC** [comment]
Closing for inactivity.

**Pull request closed without merging**
